custom.datasource.enabled=true
custom.datasource.url=jdbc:mysql://localhost:3306/employee_db
custom.datasource.username=root
custom.datasource.password=Admin@12345

server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true